import 'dart:ui';

class AppColors {
  AppColors._();
  static const Color primary = Color(0xff659DCE);
  static const Color primary7 = Color(0xffBF4904);
  static const Color white = Color(0xffFFFFFF);
  static const Color black = Color(0xff000000);
  static const Color black1 = Color(0xff0C0C0C);
  static const Color headline45 = Color(0xffBCBCBC);
  static const Color lightGrey = Color(0xffD3D3D3);
  static const Color yellow = Color(0xffFFB508);
  static const Color lavender = Color(0xffE6E6E6);
  static const Color dark4 = Color(0xff616161);
  static const Color secondary = Color(0xffBCBCBC);
  static const Color secondary7 = Color(0xff659DCE);
  static const Color secondary5 = Color(0xff487094);
  static const Color dark8 = Color(0xffD4D4D4);
  static const Color dark6 = Color(0xff9B9B9B);
  static const Color dark10 = Color(0xffF9F9F9);
  static const Color dark3 = Color(0xff434343);
  static const Color dark2 = Color(0xff242424);
  static const Color primaryAccent6 = Color(0xffFFD3B9);
  static const Color redLight = Color(0xffF6F6F6);
  static const Color gray73 = Color(0xffBABABA);
  static const Color gray98 = Color(0xffFAFAFA);
  static const Color gray87 = Color(0xffDEDEDE);
  static const Color whiteout = Color(0xffFBFBFB);
  static const Color whiteSmoke = Color(0xffF4F4F4);
  static const Color whiteSmoke7 = Color(0xffF7F7F7);
  static const Color whiteSmoke2 = Color(0xffF2F2F2);
  static const Color spanishGray = Color(0xff939393);
  static const Color nero = Color(0xff232323);
  static const Color blueRibbon = Color(0xff0066FF);
  static const Color matterhorn = Color(0xff4E4E4E);
  static const Color unicornSilver = Color(0xffE8E8E8);
  static const Color dark1 = Color(0xff151515);
  static const Color putty = Color(0xffD5946E);
  static const Color alto = Color(0xffE0E0E0);
  static const Color lightShade = Color(0xffBDD8FF);
  static const Color smalt = Color(0xff003B93);
  static const Color smokyBlack = Color(0xff0D0D0D);
  static const Color shadeGray = Color(0xffCCCCCC);
  static const Color shadeOrange = Color(0xffFFB589);
  static const Color shadeRed = Color(0xffFF1B1B);
  static const Color dark9 = Color(0xffF2F2F2);
  static const Color dark7 = Color(0xffB8B8B8);
  static const Color shadeGreen = Color(0xff34A100);
  static const Color primary7Shade = Color(0xfff8ece5);
  static const Color whiteRedShade = Color(0xffFFF3EB);
  static const Color secondry7 = Color(0xff659DCE);
  static const Color maroon1 = Color(0xffFFEEA9);
  static const Color maroon2 = Color(0xffCBE2B5);
  static const Color maroon3 = Color(0xffEECAD5);
  static const Color maroon4 = Color(0xff98E4FF);
}
