class Images {
  Images._();
  static String nutmegLogo = "assets/images/nutmeg_logo.png";
  static String email = "assets/images/email.svg";
  static String password = "assets/images/password.svg";
  static String eye = "assets/images/eye.svg";
  static String bmi = "assets/images/bmi.png";
  static String kcal = "assets/images/kcal.png";
  static String step = "assets/images/step.png";
  static String weight = "assets/images/weight.png";
  static String user = "assets/images/user.png";
  static String ai = "assets/images/ai.png";
  static String aiLogo = "assets/images/ai_logo.png";
  static String weight1 = "assets/images/weight_1.png";
  static String height = "assets/images/height.png";
  static String age = "assets/images/age.png";
  static String target = "assets/images/target.png";
  static String gender = "assets/images/gender.png";
  static String breakfast = "assets/images/breakfast.png";
  static String lunch = "assets/images/lunch.png";
  static String dinner = "assets/images/dinner.png";
  static String point = "assets/images/point.png";
  static String dinnerSnk = "assets/images/dinner_snk.png";
  static String snackEvn = "assets/images/snack_evn.png";
  static String midMngSnk = "assets/images/mid_mng_snk.png";
  static String bgImg = "assets/images/bg_img.jpg";
  static String signupBgImg = "assets/images/sign_up_bg.jpg";
  static String addUser = "assets/images/add-user.png";
  static String noDiet = "assets/images/no_diet.png";
  static String add = "assets/images/add.png";
  static String splashBg = "assets/images/splash_bg.jpg";
}
